<?php

namespace Database\Seeders;

use App\Models\PlacesOfInterest;
use Illuminate\Database\Seeder;

class PlacesOfInterestSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            // ---- Food & drink ----
            ['name' => "Gongoozler's Rest Café Boat", 'slug' => 'gongoozlers-rest', 'description' => 'Highly recommended for breakfast on the boat on a Saturday or Sunday morning. The staff are extremely friendly.', 'category' => 'Food & drink', 'sub_category' => 'Café on a canal boat', 'distance' => '0.2 miles · 4 min walk', 'is_local' => true, 'address' => 'The Stophouse, Braunston NN11 7JQ', 'phone' => '07940 973529', 'hours' => 'Seasonal — check Facebook', 'website' => null, 'is_active' => true, 'sort_order' => 1],
            ['name' => 'The Admiral Nelson', 'slug' => 'admiral-nelson', 'description' => 'A lovely walk along the canal to get there, with an excellent menu and a nice range of drinks. Sit by the water and watch the boats go past.', 'category' => 'Food & drink', 'sub_category' => 'Canalside pub and restaurant', 'distance' => '0.6 miles · 12 min walk', 'is_local' => true, 'address' => 'Dark Lane, Braunston NN11 7HJ', 'phone' => '01788 891900', 'hours' => 'Bar 12:00–23:00 · Food 12:00–15:00 and 17:00–21:00', 'website' => 'https://www.admiralnelsonbraunston.co.uk/', 'is_active' => true, 'sort_order' => 2],
            ['name' => 'The Old Plough', 'slug' => 'old-plough-braunston', 'description' => 'Traditional village pub in the centre of Braunston, well priced food and a large screen for the sport.', 'category' => 'Food & drink', 'sub_category' => 'Pub', 'distance' => '0.4 miles · 7 min walk', 'is_local' => true, 'address' => '82 High Street, Braunston NN11 7HS', 'phone' => '01788 318144', 'hours' => 'See website or Facebook', 'website' => 'https://www.oldploughbraunston.com/', 'is_active' => true, 'sort_order' => 3],
            ['name' => 'The Boathouse', 'slug' => 'boathouse-braunston', 'description' => 'Sizeable canalside pub and restaurant with a good menu. They also do a carvery most days of the week.', 'category' => 'Food & drink', 'sub_category' => 'Canalside pub and restaurant', 'distance' => '0.5 miles · 10 min walk', 'is_local' => true, 'address' => 'London Road, Braunston NN11 7HB', 'phone' => '01788 891734', 'hours' => 'Daily 11:00–23:00, kitchen hours vary', 'website' => 'https://www.boathousepub.co.uk/', 'is_active' => true, 'sort_order' => 4],
            ['name' => 'The Wheatsheaf Inn', 'slug' => 'wheatsheaf-inn-braunston', 'description' => 'A proper local, family run, in the centre of Braunston. Open log burner, pool table and skittles.', 'category' => 'Food & drink', 'sub_category' => 'Pub', 'distance' => '0.5 miles · 10 min walk', 'is_local' => true, 'address' => '10 The Green, Braunston NN11 7HW', 'phone' => '01788 890748', 'hours' => 'See local listing', 'website' => 'https://www.braunston.org.uk/org.aspx?n=The-Wheatsheaf-Inn', 'is_active' => true, 'sort_order' => 5],
            ['name' => 'The Braunston Fryer', 'slug' => 'braunston-fryer', 'description' => 'The village chip shop, in the heart of Braunston. Good quality and good value.', 'category' => 'Food & drink', 'sub_category' => 'Fish and chip takeaway', 'distance' => '0.5 miles · 11 min walk', 'is_local' => true, 'address' => '2 The Green, Braunston NN11 7HW', 'phone' => '01788 890258', 'hours' => 'Usually evenings — check Facebook', 'website' => 'http://www.thebraunstonfryer.co.uk/', 'is_active' => true, 'sort_order' => 6],
            ['name' => 'The Village Café', 'slug' => 'braunston-village-cafe', 'description' => 'Small, cosy community café. Short opening hours but excellent value and a great community feel.', 'category' => 'Food & drink', 'sub_category' => 'Café', 'distance' => '0.4 miles · 9 min walk', 'is_local' => true, 'address' => '31 High Street, Braunston NN11 7HR', 'phone' => '07774 754511', 'hours' => 'Mon–Fri 10:30–14:30, Sat 10:30–12:30, closed Sun', 'website' => 'https://www.braunstonvillagecafe.co.uk', 'is_active' => true, 'sort_order' => 7],

            // ---- Days out ----
            ['name' => 'Braunston Marina', 'slug' => 'braunston-marina-days', 'description' => 'Historic working boats, the original canal buildings and the junction of the Grand Union and Oxford canals.', 'category' => 'Days out', 'sub_category' => 'Canal heritage', 'distance' => 'On the doorstep', 'is_local' => true, 'address' => null, 'is_active' => true, 'sort_order' => 1],
            ['name' => 'Althorp House', 'slug' => 'althorp-house', 'description' => 'The historic Spencer family seat, with the exhibition of the life of Diana, Princess of Wales, and its parkland.', 'category' => 'Days out', 'sub_category' => 'Historic house', 'distance' => '16 miles · 25 min', 'address' => 'Althorp NN7 4HQ', 'website' => 'https://althorp.com', 'is_active' => true, 'sort_order' => 2],
            ['name' => 'Canons Ashby House', 'slug' => 'canons-ashby-house', 'description' => 'An Elizabethan manor house with a formal garden and priory church, cared for by the National Trust.', 'category' => 'Days out', 'sub_category' => 'National Trust', 'distance' => '17.5 miles · 30 min', 'address' => 'Canons Ashby NN12 8UA', 'website' => 'https://www.nationaltrust.org.uk/canons-ashby', 'is_active' => true, 'sort_order' => 3],
            ['name' => 'Rockingham Castle', 'slug' => 'rockingham-castle', 'description' => 'A Norman castle on a hilltop, with gardens, a maze and over 900 years of history.', 'category' => 'Days out', 'sub_category' => 'Historic castle', 'distance' => '18.5 miles · 35 min', 'address' => 'Rockingham LE16 8TH', 'website' => 'https://www.rockinghamcastle.com', 'is_active' => true, 'sort_order' => 4],
            ['name' => 'Wicksteed Park', 'slug' => 'wicksteed-park', 'description' => 'A family amusement park with rides, a lake and extensive playgrounds.', 'category' => 'Days out', 'sub_category' => 'Amusement park', 'distance' => '19 miles · 30 min', 'address' => 'Kettering NN15 6NJ', 'website' => 'https://wicksteadpark.org', 'is_active' => true, 'sort_order' => 5],
            ['name' => 'Stanwick Lakes', 'slug' => 'stanwick-lakes', 'description' => 'A nature reserve built in the gravel pits, with walking and cycling trails and a visitor centre.', 'category' => 'Days out', 'sub_category' => 'Country park', 'distance' => '19.5 miles · 30 min', 'address' => 'Stanwick NN9 6GY', 'website' => 'https://www.stanwicklakes.org.uk', 'is_active' => true, 'sort_order' => 6],
            ['name' => 'Salcey Forest', 'slug' => 'salcey-forest', 'description' => 'Ancient oak woodland with accessible trails and a tree-top walk.', 'category' => 'Days out', 'sub_category' => 'Ancient woodland', 'distance' => '20 miles · 25 min', 'address' => 'Northampton NN7 2HX', 'website' => 'https://www.forestryengland.uk/salcey-forest', 'is_active' => true, 'sort_order' => 7],
            ['name' => 'Warwick Castle', 'slug' => 'warwick-castle-days', 'description' => 'A full medieval castle experience with live shows, dungeons and the ramparts.', 'category' => 'Days out', 'sub_category' => 'Historic castle', 'distance' => '21 miles · 35 min', 'address' => 'Warwick CV34 6AH', 'website' => 'https://www.warwick-castle.com', 'is_active' => true, 'sort_order' => 8],
            ['name' => 'Silverstone Circuit', 'slug' => 'silverstone-circuit-days', 'description' => 'Home of British motorsport, with its museum, tours and driving experiences.', 'category' => 'Days out', 'sub_category' => 'Motorsport', 'distance' => '22 miles · 30 min', 'address' => 'Silverstone NN12 8TN', 'website' => 'https://www.silverstone.co.uk', 'is_active' => true, 'sort_order' => 9],
            ['name' => 'Draycote Water', 'slug' => 'draycote-water', 'description' => 'A large reservoir with a flat reservoir-side path popular with walkers and cyclists.', 'category' => 'Days out', 'sub_category' => 'Reservoir and country park', 'distance' => '23 miles · 36 min', 'address' => 'Kites Hardwick CV23 8AB', 'is_active' => true, 'sort_order' => 10],
            ['name' => 'Oxford', 'slug' => 'oxford-city', 'description' => 'The university city, with its colleges, museums, Botanic Garden and the river.', 'category' => 'Days out', 'sub_category' => 'University city and museums', 'distance' => '23 miles · 40 min', 'address' => 'Oxford OX1 2JD', 'is_active' => true, 'sort_order' => 11],
            ['name' => 'Cotswold Wildlife Park', 'slug' => 'cotswold-wildlife-park', 'description' => 'A wildlife park set in landscaped gardens with a wide range of animals and feedings.', 'category' => 'Days out', 'sub_category' => 'Wildlife park', 'distance' => '24 miles · 45 min', 'address' => 'Burford OX18 4JP', 'website' => 'https://www.cotswoldwildlifepark.co.uk', 'is_active' => true, 'sort_order' => 12],
            ['name' => 'Blenheim Palace', 'slug' => 'blenheim-palace', 'description' => 'A UNESCO World Heritage site, the birthplace of Winston Churchill, with stunning parkland.', 'category' => 'Days out', 'sub_category' => 'UNESCO World Heritage site', 'distance' => '25 miles · 45 min', 'address' => 'Woodstock OX20 1PP', 'website' => 'https://www.blenheimpalace.com', 'is_active' => true, 'sort_order' => 13],
            ['name' => 'Cotswold Water Park', 'slug' => 'cotswold-water-park', 'description' => 'The largest marl lake complex in Europe, great for watersports, swimming and nature.', 'category' => 'Days out', 'sub_category' => 'Leisure and nature reserve', 'distance' => '26 miles · 50 min', 'address' => 'Cirencester GL7 6DF', 'is_active' => true, 'sort_order' => 14],
            ['name' => 'Cheltenham Racecourse', 'slug' => 'cheltenham-racecourse', 'description' => 'Home of the Cheltenham Festival and jump racing at the heart of the Cotswolds.', 'category' => 'Days out', 'sub_category' => 'Horse racing', 'distance' => '27 miles · 50 min', 'address' => 'Cheltenham GL50 4SH', 'website' => 'https://www.thejockeyclub.co.uk/cheltenham', 'is_active' => true, 'sort_order' => 15],
            ['name' => 'Stratford-upon-Avon', 'slug' => 'stratford-upon-avon-days', 'description' => 'Shakespeare’s hometown, with the theatres, the river and the old town centre.', 'category' => 'Days out', 'sub_category' => 'Historic town', 'distance' => '28 miles · 50 min', 'address' => 'Stratford-upon-Avon CV37 6EF', 'is_active' => true, 'sort_order' => 16],
            ['name' => "Shakespeare's Birthplace", 'slug' => 'shakespeares-birthplace', 'description' => 'The house where William Shakespeare was born, restored as it would have been in his day.', 'category' => 'Days out', 'sub_category' => 'Historic site', 'distance' => '28 miles · 50 min', 'address' => 'Stratford-upon-Avon CV37 6QW', 'website' => 'https://www.shakespeare.org.uk', 'is_active' => true, 'sort_order' => 17],
            ['name' => 'Warwick Racecourse', 'slug' => 'warwick-racecourse', 'description' => 'A friendly, family-oriented racecourse with jump and flat meetings through the year.', 'category' => 'Days out', 'sub_category' => 'Horse racing', 'distance' => '29 miles · 50 min', 'address' => 'Warwick CV34 6HN', 'website' => 'https://www.warwickracecourse.co.uk', 'is_active' => true, 'sort_order' => 18],
            ['name' => 'Cotswold Farm Park', 'slug' => 'cotswold-farm-park', 'description' => 'Adam Henson’s farm park, with rare-breed animals and activities for children.', 'category' => 'Days out', 'sub_category' => 'Farm attraction', 'distance' => '30 miles · 55 min', 'address' => 'Guiting Power GL54 5UG', 'website' => 'https://cotswoldfarmpark.co.uk', 'is_active' => true, 'sort_order' => 19],
            ['name' => 'Broadway Tower', 'slug' => 'broadway-tower', 'description' => 'A folly on the Cotswold escarpment with far-reaching views across five counties.', 'category' => 'Days out', 'sub_category' => 'Historic tower', 'distance' => '31 miles · 55 min', 'address' => 'Broadway WR12 7LB', 'website' => 'https://www.broadwaytower.co.uk', 'is_active' => true, 'sort_order' => 20],
            ['name' => 'Oxford Botanic Garden', 'slug' => 'oxford-botanic-garden', 'description' => 'The oldest botanic garden in Britain, a green haven by the river in the city.', 'category' => 'Days out', 'sub_category' => 'Botanical garden', 'distance' => '32 miles · 50 min', 'address' => 'Oxford OX1 4AZ', 'is_active' => true, 'sort_order' => 21],
            ['name' => 'Cotswold Distillery', 'slug' => 'cotswold-distillery', 'description' => 'A working distillery in the Cotswolds with tours, tastings and a shop.', 'category' => 'Days out', 'sub_category' => 'Distillery and visitor centre', 'distance' => '34 miles · 60 min', 'address' => 'Stourton GL56 0RH', 'website' => 'https://www.cotswolddistillery.com', 'is_active' => true, 'sort_order' => 22],
            ['name' => 'Cotswold Lavender', 'slug' => 'cotswold-lavender', 'description' => 'A 40-acre lavender farm, at its most striking when in bloom in high summer.', 'category' => 'Days out', 'sub_category' => 'Lavender farm', 'distance' => '36 miles · 60 min', 'address' => 'Snowshill WR12 7JU', 'website' => 'https://cotswoldlavender.co.uk', 'is_active' => true, 'sort_order' => 23],
            ['name' => 'Cotswold Way National Trail', 'slug' => 'cotswold-way', 'description' => 'A 102-mile trail along the Cotswold escarpment, with superb sections close by for a day walk.', 'category' => 'Days out', 'sub_category' => 'Hiking trail', 'distance' => '37 miles · 65 min', 'address' => 'Chipping Campden GL55 6AL', 'is_active' => true, 'sort_order' => 24],
            ['name' => 'Oxford University Museum of Natural History', 'slug' => 'oxford-natural-history-museum', 'description' => 'Victorian museum of natural history with its famous dinosaur skeletons and Pitt Rivers collection.', 'category' => 'Days out', 'sub_category' => 'Museum', 'distance' => '38 miles · 60 min', 'address' => 'Oxford OX1 3PW', 'website' => 'https://oumnh.ox.ac.uk', 'is_active' => true, 'sort_order' => 25],
            ['name' => 'Bicester Heritage', 'slug' => 'bicester-heritage', 'description' => 'A preserved WWII RAF station now the home of vintage motoring, with events through the year.', 'category' => 'Days out', 'sub_category' => 'Vintage aviation and motoring', 'distance' => '39 miles · 65 min', 'address' => 'Bicester OX27 8AL', 'website' => 'https://www.bicesterheritage.co.uk', 'is_active' => true, 'sort_order' => 26],
            ['name' => 'Cheltenham Art Gallery & Museum', 'slug' => 'cheltenham-art-gallery', 'description' => 'A free museum with the Arts and Crafts collection and local history galleries.', 'category' => 'Days out', 'sub_category' => 'Art museum', 'distance' => '40 miles · 65 min', 'address' => 'Cheltenham GL50 3JT', 'website' => 'https://www.cheltenhammuseum.org.uk', 'is_active' => true, 'sort_order' => 27],
            ['name' => 'Worcester Cathedral', 'slug' => 'worcester-cathedral', 'description' => 'A magnificent medieval cathedral on the banks of the River Severn.', 'category' => 'Days out', 'sub_category' => 'Historic cathedral', 'distance' => '41 miles · 70 min', 'address' => 'Worcester WR1 2LA', 'website' => 'https://www.worcestercathedral.org.uk', 'is_active' => true, 'sort_order' => 28],
            ['name' => 'Cotswold Falconry Centre', 'slug' => 'cotswold-falconry-centre', 'description' => 'Daily flying displays of birds of prey in a wooded valley.', 'category' => 'Days out', 'sub_category' => 'Birds of prey', 'distance' => '42 miles · 70 min', 'address' => 'Moreton-in-Marsh GL56 0RH', 'website' => 'https://www.cotswold-falconry.co.uk', 'is_active' => true, 'sort_order' => 29],
            ['name' => 'Stratford Butterfly Farm', 'slug' => 'stratford-butterfly-farm', 'description' => 'A tropical butterfly farm and insect zoo beside the river in Stratford.', 'category' => 'Days out', 'sub_category' => 'Butterfly centre', 'distance' => '44 miles · 70 min', 'address' => 'Stratford-upon-Avon CV37 6TB', 'website' => 'https://www.butterflyfarm.co.uk', 'is_active' => true, 'sort_order' => 30],
            ['name' => 'Oxford Castle & Prison', 'slug' => 'oxford-castle-prison', 'description' => 'Explore 1,000 years of history at Oxford’s restored medieval castle and prison.', 'category' => 'Days out', 'sub_category' => 'Historic site', 'distance' => '45 miles · 70 min', 'address' => 'Oxford OX1 1AY', 'website' => 'https://www.oxfordcastleandprison.co.uk', 'is_active' => true, 'sort_order' => 31],
            ['name' => 'Bicester Village', 'slug' => 'bicester-village', 'description' => 'A designer shopping outlet village with over 160 boutiques and restaurants.', 'category' => 'Days out', 'sub_category' => 'Shopping outlet', 'distance' => '46 miles · 75 min', 'address' => 'Bicester OX26 6WD', 'website' => 'https://www.bicestervillage.com', 'is_active' => true, 'sort_order' => 32],
            ['name' => 'Cheltenham', 'slug' => 'cheltenham-town', 'description' => 'A handsome Regency spa town of wide streets, gardens and independent shops.', 'category' => 'Days out', 'sub_category' => 'Historic spa town', 'distance' => '47 miles · 75 min', 'address' => 'Cheltenham GL50 1NN', 'is_active' => true, 'sort_order' => 33],
            ['name' => 'Worcester Porcelain Museum', 'slug' => 'worcester-porcelain-museum', 'description' => 'The story of Royal Worcester porcelain, including the world’s largest collection.', 'category' => 'Days out', 'sub_category' => 'Museum', 'distance' => '48 miles · 80 min', 'address' => 'Worcester WR1 2ND', 'is_active' => true, 'sort_order' => 34],
        ];

        foreach ($places as $place) {
            PlacesOfInterest::firstOrCreate(['slug' => $place['slug']], $place);
        }
    }
}
