@extends('layouts.admin.app')
@section('title', 'Revenue')
@section('content')
<div class="ch-page-header"><div><h4>Revenue intelligence</h4></div></div>
<div class="row g-3 mb-4">
    @foreach ([
        ['Revenue', '£'.number_format($stats['revenue'], 2)],
        ['Occupancy', $stats['occupancy'].'%'],
        ['ADR', '£'.number_format($stats['adr'], 2)],
        ['RevPAR', '£'.number_format($stats['revpar'], 2)],
        ['Direct', $stats['direct_bookings']],
        ['OTA', $stats['ota_bookings']],
        ['Avg booking', '£'.number_format($stats['average_booking_value'], 2)],
        ['Cancel rate', $stats['cancellation_rate'].'%'],
    ] as $card)
        <div class="col-6 col-md-3">
            <div class="ch-stat-card"><div><div class="ch-stat-value">{{ $card[1] }}</div><div class="ch-stat-label">{{ $card[0] }}</div></div></div>
        </div>
    @endforeach
</div>
<div class="card border-0 shadow-sm">
    <div class="card-body">
        <canvas id="revenueChart" height="120"></canvas>
    </div>
</div>
<div class="card border-0 shadow-sm mt-4">
    <div class="card-header bg-white">
        <div class="fw-semibold">Snapshot history</div>
        <div class="small text-muted">Nightly revenue snapshots generated by the scheduled job.</div>
    </div>
    <div class="table-responsive">
        <table class="table table-sm align-middle mb-0">
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="text-end">Revenue</th>
                    <th class="text-end">ADR</th>
                    <th class="text-end">RevPAR</th>
                    <th class="text-end">Occupancy</th>
                    <th class="text-end">Bookings</th>
                    <th class="text-end">Cancellations</th>
                    <th class="text-end">Direct</th>
                    <th class="text-end">OTA</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($snapshots as $snapshot)
                    <tr>
                        <td>{{ $snapshot->snapshot_date }}</td>
                        <td class="text-end">£{{ number_format($snapshot->revenue, 2) }}</td>
                        <td class="text-end">£{{ number_format($snapshot->adr, 2) }}</td>
                        <td class="text-end">£{{ number_format($snapshot->revpar, 2) }}</td>
                        <td class="text-end">{{ $snapshot->occupancy_pct }}%</td>
                        <td class="text-end">{{ $snapshot->bookings_count }}</td>
                        <td class="text-end">{{ $snapshot->cancellations_count }}</td>
                        <td class="text-end">{{ $snapshot->direct_bookings }}</td>
                        <td class="text-end">{{ $snapshot->ota_bookings }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9" class="text-center text-muted py-3">No snapshots captured yet. The nightly job creates them automatically.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const series = @json($series);
    new Chart(document.getElementById('revenueChart'), {
        type: 'line',
        data: {
            labels: series.labels,
            datasets: [{ label: 'Revenue', data: series.revenue, borderColor: '#1f6f43' }]
        }
    });
});
</script>
@endpush
@endsection
