{{--
The MIT License (MIT)

Copyright (c) 2014-2016 Jack O'Connor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

--}}
{{-- Dial codes: intl-tel-input v25.3.1 (MIT), https://github.com/jackocnr/intl-tel-input --}}
@php
    $phoneCountries = [
        ['gb', '+44', '🇬🇧 United Kingdom'],
        ['af', '+93', '🇦🇫 Afghanistan'],
        ['ax', '+358', '🇦🇽 Åland Islands'],
        ['al', '+355', '🇦🇱 Albania'],
        ['dz', '+213', '🇩🇿 Algeria'],
        ['as', '+1', '🇦🇸 American Samoa'],
        ['ad', '+376', '🇦🇩 Andorra'],
        ['ao', '+244', '🇦🇴 Angola'],
        ['ai', '+1', '🇦🇮 Anguilla'],
        ['ag', '+1', '🇦🇬 Antigua and Barbuda'],
        ['ar', '+54', '🇦🇷 Argentina'],
        ['am', '+374', '🇦🇲 Armenia'],
        ['aw', '+297', '🇦🇼 Aruba'],
        ['ac', '+247', '🇦🇨 Ascension Island'],
        ['au', '+61', '🇦🇺 Australia'],
        ['at', '+43', '🇦🇹 Austria'],
        ['az', '+994', '🇦🇿 Azerbaijan'],
        ['bs', '+1', '🇧🇸 Bahamas'],
        ['bh', '+973', '🇧🇭 Bahrain'],
        ['bd', '+880', '🇧🇩 Bangladesh'],
        ['bb', '+1', '🇧🇧 Barbados'],
        ['by', '+375', '🇧🇾 Belarus'],
        ['be', '+32', '🇧🇪 Belgium'],
        ['bz', '+501', '🇧🇿 Belize'],
        ['bj', '+229', '🇧🇯 Benin'],
        ['bm', '+1', '🇧🇲 Bermuda'],
        ['bt', '+975', '🇧🇹 Bhutan'],
        ['bo', '+591', '🇧🇴 Bolivia'],
        ['ba', '+387', '🇧🇦 Bosnia and Herzegovina'],
        ['bw', '+267', '🇧🇼 Botswana'],
        ['br', '+55', '🇧🇷 Brazil'],
        ['io', '+246', '🇮🇴 British Indian Ocean Territory'],
        ['vg', '+1', '🇻🇬 British Virgin Islands'],
        ['bn', '+673', '🇧🇳 Brunei'],
        ['bg', '+359', '🇧🇬 Bulgaria'],
        ['bf', '+226', '🇧🇫 Burkina Faso'],
        ['bi', '+257', '🇧🇮 Burundi'],
        ['kh', '+855', '🇰🇭 Cambodia'],
        ['cm', '+237', '🇨🇲 Cameroon'],
        ['ca', '+1', '🇨🇦 Canada'],
        ['cv', '+238', '🇨🇻 Cape Verde'],
        ['bq', '+599', '🇧🇶 Caribbean Netherlands'],
        ['ky', '+1', '🇰🇾 Cayman Islands'],
        ['cf', '+236', '🇨🇫 Central African Republic'],
        ['td', '+235', '🇹🇩 Chad'],
        ['cl', '+56', '🇨🇱 Chile'],
        ['cn', '+86', '🇨🇳 China'],
        ['cx', '+61', '🇨🇽 Christmas Island'],
        ['cc', '+61', '🇨🇨 Cocos (Keeling) Islands'],
        ['co', '+57', '🇨🇴 Colombia'],
        ['km', '+269', '🇰🇲 Comoros'],
        ['cg', '+242', '🇨🇬 Congo (Brazzaville)'],
        ['cd', '+243', '🇨🇩 Congo (Kinshasa)'],
        ['ck', '+682', '🇨🇰 Cook Islands'],
        ['cr', '+506', '🇨🇷 Costa Rica'],
        ['ci', '+225', '🇨🇮 Côte d\'Ivoire'],
        ['hr', '+385', '🇭🇷 Croatia'],
        ['cu', '+53', '🇨🇺 Cuba'],
        ['cw', '+599', '🇨🇼 Curaçao'],
        ['cy', '+357', '🇨🇾 Cyprus'],
        ['cz', '+420', '🇨🇿 Czech Republic'],
        ['dk', '+45', '🇩🇰 Denmark'],
        ['dj', '+253', '🇩🇯 Djibouti'],
        ['dm', '+1', '🇩🇲 Dominica'],
        ['do', '+1', '🇩🇴 Dominican Republic'],
        ['ec', '+593', '🇪🇨 Ecuador'],
        ['eg', '+20', '🇪🇬 Egypt'],
        ['sv', '+503', '🇸🇻 El Salvador'],
        ['gq', '+240', '🇬🇶 Equatorial Guinea'],
        ['er', '+291', '🇪🇷 Eritrea'],
        ['ee', '+372', '🇪🇪 Estonia'],
        ['sz', '+268', '🇸🇿 Eswatini'],
        ['et', '+251', '🇪🇹 Ethiopia'],
        ['fk', '+500', '🇫🇰 Falkland Islands (Malvinas)'],
        ['fo', '+298', '🇫🇴 Faroe Islands'],
        ['fj', '+679', '🇫🇯 Fiji'],
        ['fi', '+358', '🇫🇮 Finland'],
        ['fr', '+33', '🇫🇷 France'],
        ['gf', '+594', '🇬🇫 French Guiana'],
        ['pf', '+689', '🇵🇫 French Polynesia'],
        ['ga', '+241', '🇬🇦 Gabon'],
        ['gm', '+220', '🇬🇲 Gambia'],
        ['ge', '+995', '🇬🇪 Georgia'],
        ['de', '+49', '🇩🇪 Germany'],
        ['gh', '+233', '🇬🇭 Ghana'],
        ['gi', '+350', '🇬🇮 Gibraltar'],
        ['gr', '+30', '🇬🇷 Greece'],
        ['gl', '+299', '🇬🇱 Greenland'],
        ['gd', '+1', '🇬🇩 Grenada'],
        ['gp', '+590', '🇬🇵 Guadeloupe'],
        ['gu', '+1', '🇬🇺 Guam'],
        ['gt', '+502', '🇬🇹 Guatemala'],
        ['gg', '+44', '🇬🇬 Guernsey'],
        ['gn', '+224', '🇬🇳 Guinea'],
        ['gw', '+245', '🇬🇼 Guinea-Bissau'],
        ['gy', '+592', '🇬🇾 Guyana'],
        ['ht', '+509', '🇭🇹 Haiti'],
        ['hn', '+504', '🇭🇳 Honduras'],
        ['hk', '+852', '🇭🇰 Hong Kong SAR China'],
        ['hu', '+36', '🇭🇺 Hungary'],
        ['is', '+354', '🇮🇸 Iceland'],
        ['in', '+91', '🇮🇳 India'],
        ['id', '+62', '🇮🇩 Indonesia'],
        ['ir', '+98', '🇮🇷 Iran'],
        ['iq', '+964', '🇮🇶 Iraq'],
        ['ie', '+353', '🇮🇪 Ireland'],
        ['im', '+44', '🇮🇲 Isle of Man'],
        ['il', '+972', '🇮🇱 Israel'],
        ['it', '+39', '🇮🇹 Italy'],
        ['jm', '+1', '🇯🇲 Jamaica'],
        ['jp', '+81', '🇯🇵 Japan'],
        ['je', '+44', '🇯🇪 Jersey'],
        ['jo', '+962', '🇯🇴 Jordan'],
        ['kz', '+7', '🇰🇿 Kazakhstan'],
        ['ke', '+254', '🇰🇪 Kenya'],
        ['ki', '+686', '🇰🇮 Kiribati'],
        ['xk', '+383', '🇽🇰 Kosovo'],
        ['kw', '+965', '🇰🇼 Kuwait'],
        ['kg', '+996', '🇰🇬 Kyrgyzstan'],
        ['la', '+856', '🇱🇦 Laos'],
        ['lv', '+371', '🇱🇻 Latvia'],
        ['lb', '+961', '🇱🇧 Lebanon'],
        ['ls', '+266', '🇱🇸 Lesotho'],
        ['lr', '+231', '🇱🇷 Liberia'],
        ['ly', '+218', '🇱🇾 Libya'],
        ['li', '+423', '🇱🇮 Liechtenstein'],
        ['lt', '+370', '🇱🇹 Lithuania'],
        ['lu', '+352', '🇱🇺 Luxembourg'],
        ['mo', '+853', '🇲🇴 Macao SAR China'],
        ['mg', '+261', '🇲🇬 Madagascar'],
        ['mw', '+265', '🇲🇼 Malawi'],
        ['my', '+60', '🇲🇾 Malaysia'],
        ['mv', '+960', '🇲🇻 Maldives'],
        ['ml', '+223', '🇲🇱 Mali'],
        ['mt', '+356', '🇲🇹 Malta'],
        ['mh', '+692', '🇲🇭 Marshall Islands'],
        ['mq', '+596', '🇲🇶 Martinique'],
        ['mr', '+222', '🇲🇷 Mauritania'],
        ['mu', '+230', '🇲🇺 Mauritius'],
        ['yt', '+262', '🇾🇹 Mayotte'],
        ['mx', '+52', '🇲🇽 Mexico'],
        ['fm', '+691', '🇫🇲 Micronesia'],
        ['md', '+373', '🇲🇩 Moldova'],
        ['mc', '+377', '🇲🇨 Monaco'],
        ['mn', '+976', '🇲🇳 Mongolia'],
        ['me', '+382', '🇲🇪 Montenegro'],
        ['ms', '+1', '🇲🇸 Montserrat'],
        ['ma', '+212', '🇲🇦 Morocco'],
        ['mz', '+258', '🇲🇿 Mozambique'],
        ['mm', '+95', '🇲🇲 Myanmar (Burma)'],
        ['na', '+264', '🇳🇦 Namibia'],
        ['nr', '+674', '🇳🇷 Nauru'],
        ['np', '+977', '🇳🇵 Nepal'],
        ['nl', '+31', '🇳🇱 Netherlands'],
        ['nc', '+687', '🇳🇨 New Caledonia'],
        ['nz', '+64', '🇳🇿 New Zealand'],
        ['ni', '+505', '🇳🇮 Nicaragua'],
        ['ne', '+227', '🇳🇪 Niger'],
        ['ng', '+234', '🇳🇬 Nigeria'],
        ['nu', '+683', '🇳🇺 Niue'],
        ['nf', '+672', '🇳🇫 Norfolk Island'],
        ['kp', '+850', '🇰🇵 North Korea'],
        ['mk', '+389', '🇲🇰 North Macedonia'],
        ['mp', '+1', '🇲🇵 Northern Mariana Islands'],
        ['no', '+47', '🇳🇴 Norway'],
        ['om', '+968', '🇴🇲 Oman'],
        ['pk', '+92', '🇵🇰 Pakistan'],
        ['pw', '+680', '🇵🇼 Palau'],
        ['ps', '+970', '🇵🇸 Palestinian Territories'],
        ['pa', '+507', '🇵🇦 Panama'],
        ['pg', '+675', '🇵🇬 Papua New Guinea'],
        ['py', '+595', '🇵🇾 Paraguay'],
        ['pe', '+51', '🇵🇪 Peru'],
        ['ph', '+63', '🇵🇭 Philippines'],
        ['pl', '+48', '🇵🇱 Poland'],
        ['pt', '+351', '🇵🇹 Portugal'],
        ['pr', '+1', '🇵🇷 Puerto Rico'],
        ['qa', '+974', '🇶🇦 Qatar'],
        ['re', '+262', '🇷🇪 Réunion'],
        ['ro', '+40', '🇷🇴 Romania'],
        ['ru', '+7', '🇷🇺 Russia'],
        ['rw', '+250', '🇷🇼 Rwanda'],
        ['ws', '+685', '🇼🇸 Samoa'],
        ['sm', '+378', '🇸🇲 San Marino'],
        ['st', '+239', '🇸🇹 São Tomé & Príncipe'],
        ['sa', '+966', '🇸🇦 Saudi Arabia'],
        ['sn', '+221', '🇸🇳 Senegal'],
        ['rs', '+381', '🇷🇸 Serbia'],
        ['sc', '+248', '🇸🇨 Seychelles'],
        ['sl', '+232', '🇸🇱 Sierra Leone'],
        ['sg', '+65', '🇸🇬 Singapore'],
        ['sx', '+1', '🇸🇽 Sint Maarten'],
        ['sk', '+421', '🇸🇰 Slovakia'],
        ['si', '+386', '🇸🇮 Slovenia'],
        ['sb', '+677', '🇸🇧 Solomon Islands'],
        ['so', '+252', '🇸🇴 Somalia'],
        ['za', '+27', '🇿🇦 South Africa'],
        ['kr', '+82', '🇰🇷 South Korea'],
        ['ss', '+211', '🇸🇸 South Sudan'],
        ['es', '+34', '🇪🇸 Spain'],
        ['lk', '+94', '🇱🇰 Sri Lanka'],
        ['bl', '+590', '🇧🇱 St. Barthélemy'],
        ['sh', '+290', '🇸🇭 St. Helena'],
        ['kn', '+1', '🇰🇳 St. Kitts & Nevis'],
        ['lc', '+1', '🇱🇨 St. Lucia'],
        ['mf', '+590', '🇲🇫 St. Martin'],
        ['pm', '+508', '🇵🇲 St. Pierre & Miquelon'],
        ['vc', '+1', '🇻🇨 St. Vincent & Grenadines'],
        ['sd', '+249', '🇸🇩 Sudan'],
        ['sr', '+597', '🇸🇷 Suriname'],
        ['sj', '+47', '🇸🇯 Svalbard & Jan Mayen'],
        ['se', '+46', '🇸🇪 Sweden'],
        ['ch', '+41', '🇨🇭 Switzerland'],
        ['sy', '+963', '🇸🇾 Syria'],
        ['tw', '+886', '🇹🇼 Taiwan'],
        ['tj', '+992', '🇹🇯 Tajikistan'],
        ['tz', '+255', '🇹🇿 Tanzania'],
        ['th', '+66', '🇹🇭 Thailand'],
        ['tl', '+670', '🇹🇱 Timor-Leste'],
        ['tg', '+228', '🇹🇬 Togo'],
        ['tk', '+690', '🇹🇰 Tokelau'],
        ['to', '+676', '🇹🇴 Tonga'],
        ['tt', '+1', '🇹🇹 Trinidad & Tobago'],
        ['tn', '+216', '🇹🇳 Tunisia'],
        ['tr', '+90', '🇹🇷 Turkey'],
        ['tm', '+993', '🇹🇲 Turkmenistan'],
        ['tc', '+1', '🇹🇨 Turks & Caicos Islands'],
        ['tv', '+688', '🇹🇻 Tuvalu'],
        ['vi', '+1', '🇻🇮 U.S. Virgin Islands'],
        ['ug', '+256', '🇺🇬 Uganda'],
        ['ua', '+380', '🇺🇦 Ukraine'],
        ['ae', '+971', '🇦🇪 United Arab Emirates'],
        ['us', '+1', '🇺🇸 United States'],
        ['uy', '+598', '🇺🇾 Uruguay'],
        ['uz', '+998', '🇺🇿 Uzbekistan'],
        ['vu', '+678', '🇻🇺 Vanuatu'],
        ['va', '+39', '🇻🇦 Vatican City'],
        ['ve', '+58', '🇻🇪 Venezuela'],
        ['vn', '+84', '🇻🇳 Vietnam'],
        ['wf', '+681', '🇼🇫 Wallis & Futuna'],
        ['eh', '+212', '🇪🇭 Western Sahara'],
        ['ye', '+967', '🇾🇪 Yemen'],
        ['zm', '+260', '🇿🇲 Zambia'],
        ['zw', '+263', '🇿🇼 Zimbabwe'],
    ];
    $phoneCodeSelected = false;
@endphp
@foreach ($phoneCountries as [$countryIso, $dialCode, $countryLabel])
    @php($selectPhoneCode = ! $phoneCodeSelected && old('phone_code', '+44') === $dialCode)
    <option value="{{ $dialCode }}" data-country="{{ $countryIso }}" @selected($selectPhoneCode)>{{ $countryLabel }} {{ $dialCode }}</option>
    @php($phoneCodeSelected = $phoneCodeSelected || $selectPhoneCode)
@endforeach
